trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'ImportantApp.HardMath/*'
      - 'ImportantApp.SimpleMath/*'

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: '[Dotnet] Install SDK and Runtime'
  inputs:
    packageType: 'sdk'
    version: '7.x'

- task: DotNetCoreCLI@2
  displayName: '[Dotnet] Build project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration=$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: '[Dotnet] Pack class libraries'
  inputs:
    command: 'pack'
    packagesToPack: 'ImportantApp.HardMath/*.csproj;ImportantApp.SimpleMath/*.csproj'
    configuration: '$(buildConfiguration)'
    nobuild: true
    versioningScheme: 'byBuildNumber'

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(vstsFeed)'