trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'ImportantApp.HardMath/*'
      - 'ImportantApp.SimpleMath/*'

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: '[Dotnet] Install SDK and Runtime'
  inputs:
    packageType: 'sdk'
    version: '7.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration=Release'
